# Uncomment the next line to define a global platform for your project
# platform :ios, '12.2'

target 'confios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for confios
  pod 'common', :path => '../android/common'
  pod 'Swinject'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'MaterialComponents/Cards'

  target 'confiosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'confiosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
